export enum Providers {
  I_USER_SERVICE = 'I_USER_SERVICE',
  I_USER_REPOSITORY = 'I_USER_REPOSITORY',
  I_ACCOUNT_REPOSITORY = 'I_ACCOUNT_REPOSITORY',
  I_ACCOUNT_SERVICE = 'I_ACCOUNT_SERVICE',
  I_STOCKS_SERVICE = 'I_STOCKS_SERVICE',
  I_GOOGLE_SERVICE = 'I_GOOGLE_SERVICE',
  I_AUTH_SERVICE = 'I_AUTH_SERVICE',
  I_IEX_SERVICE = 'I_IEX_SERVICE',
}
